const express = require('express')
const router = express.Router()
const { verifyUserToken, verifyEmployeeToken, adminToken, employeeToken } = require('../middleware/auth')
const productCtrl = require('../controller/product')
const orderCtrl = require('../controller/order')
router.post('/', verifyEmployeeToken, productCtrl.createProduct)
router.delete('/:id', verifyEmployeeToken, adminToken, productCtrl.deleteProduct)
router.put('/:id', verifyUserToken, adminToken, productCtrl.updateProduct)
router.get('/', productCtrl.getAllProducts)
router.get('/:id', productCtrl.getProduct)
router.post('/searchSpecificProduct', productCtrl.searchSpecificProduct)
router.post('/productByCategory', productCtrl.getProductByCategory)
router.post('/filterProduct', productCtrl.filterProduct)

router.get('/func/getFiveNewestProducts', verifyEmployeeToken, productCtrl.getFiveNewestProducts)
router.get('/top', verifyUserToken, productCtrl.getTop10Products)
router.post('/:id/review', verifyUserToken, productCtrl.createProductReview)
router.patch('/:id/review', verifyUserToken, productCtrl.updateProductReview)
router.delete('/:id/review', verifyUserToken, productCtrl.deleteProductReview)
router.get('/:id/review', verifyUserToken, productCtrl.getAllReviews)
router.get('/id:review/user', verifyUserToken, productCtrl.getUsersFromReviews)
router.get('/func/getMostSoldProducts', verifyEmployeeToken, productCtrl.getMostSoldProducts)
module.exports = router
